# Generated by Django 3.2 on 2021-06-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('son', 'Son'), ('brother', 'Brother'), ('grandson', 'Grandson'), ('daughter', 'Daughter'), ('sister', 'Sister'), ('granddaughter', 'Granddaughter'), ('father', 'Father'), ('husband', 'Husband'), ('mother', 'Mother'), ('wife', 'Wife'), ('bride', 'Bride'), ('grandpa', 'Grandpa'), ('grandma', 'Grandma')], default='son', max_length=255),
            preserve_default=False,
        ),
    ]
