# Generated by Django 3.2 on 2021-06-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('son', 'Son'), ('brother', 'Brother'), ('grandson', 'Grandson'), ('daughter', 'Daughter'), ('sister', 'Sister'), ('granddaughter', 'Granddaughter'), ('father', 'Father'), ('husband', 'Husband'), ('mother', 'Mother'), ('wife', 'Wife'), ('bride', 'Bride'), ('grandfather', 'Grandfather'), ('grandmother', 'Grandmother')], max_length=255),
        ),
    ]
