# Generated by Django 3.2 on 2021-05-07 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_items', models.CharField(max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('clothes', 'Clothes'), ('food', 'Food'), ('education', 'Education'), ('household_expense', 'Household Expense')], max_length=255)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
