# Generated by Django 3.2 on 2021-05-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_alter_userexpense_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userexpense',
            old_name='name_of_items',
            new_name='items',
        ),
        migrations.AlterField(
            model_name='userexpense',
            name='category',
            field=models.CharField(choices=[('clothes', 'Clothes'), ('food', 'Food'), ('education', 'Education'), ('household_expense', 'Household Expenses')], max_length=255),
        ),
    ]
